---

- name: download and extract the sessionmanager-bundle
  unarchive:
    src: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip"
    dest: /Users/peter.buckley
    remote_src: yes
  tags: ['sess']

- name: install session-manager bundle
  command: "/Users/peter.buckley/sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin"
  become: yes
  tags: ['sess']
